<sidebar-tab
    name="annotations"
    icon="map-marker-alt"
    title="Annotations"
    class="sidebar__tab--nopad"
    :highlight="hasActiveAnnotationFilter"
    >
        <annotations-tab
            :annotations="filteredAnnotations"
            :selected-annotations="selectedAnnotations"
            :annotation-filters="annotationFilters"
            :can-detach-others="@can('forceEditIn', $video) true @else false @endcan"
            :has-active-filter="hasActiveAnnotationFilter"
            :own-user-id="{{$user->id}}"
            v-on:select="selectAnnotation"
            v-on:deselect="deselectAnnotation"
            v-on:detach="detachAnnotationLabel"
            v-on:select-filter="setActiveAnnotationFilter"
            v-on:unselect-filter="resetAnnotationFilter"
            ></annotations-tab>
</sidebar-tab>
