<sidebar-tab
    name="annotations"
    icon="map-marker-alt"
    title="Annotations"
    class="sidebar__tab--nopad"
    :highlight="hasActiveAnnotationFilter"
    >
        <annotations-tab
            :annotations="filteredAnnotations"
            :all-annotations="annotations"
            :total-annotation-count="annotationCount"
            :selected-annotations="selectedAnnotations"
            :can-detach-others="@can('forceEditIn', $volume) true @else false @endcan"
            :has-active-filter="hasActiveAnnotationFilter"
            :own-user-id="{{$user->id}}"
            :annotations-hidden-by-filter="annotationsHiddenByFilter"
            v-on:select="selectAnnotation"
            v-on:deselect="deselectAnnotation"
            v-on:detach="detachAnnotationLabel"
            v-on:select-filter="setActiveAnnotationFilter"
            v-on:unselect-filter="resetAnnotationFilter"
            ></annotations-tab>
</sidebar-tab>
