name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Set registry authentication token
      run: echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint
