<labels-tab
    v-cloak
    :volume-id="volumeId"
    :show-labels="showLabels"
    :loading-labels="loadingLabels"
    type="{{$type}}"
    v-on:select="handleSelectedLabel"
    v-on:deselect="handleDeselectedLabel"
    v-on:enable-labels="enableLabels"
    v-on:disable-labels="disableLabels"
    ></labels-tab>
