name: Lint PHP

on:
  push:
    branches:
      - master
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'

jobs:
  lint-php:

    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --prefer-dist --ignore-platform-reqs

    - name: Copy .env
      run: cp .env.example .env

    - name: Set testing key
      run: echo "APP_KEY=base64:STZFA4bQKDjE2mlpRPmsJ/okG0eCh4RHd9BghtZeYmQ=" >> .env

    - name: Run Linter
      run: composer lint -- --error-format=github

  cs-php:

    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: cs2pr

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --prefer-dist --ignore-platform-reqs

    - name: Copy .env
      run: cp .env.example .env

    - name: Set testing key
      run: echo "APP_KEY=base64:STZFA4bQKDjE2mlpRPmsJ/okG0eCh4RHd9BghtZeYmQ=" >> .env

    - name: Run PHP-CS fixer and cs2pr
      run: composer fix -- -vvv --dry-run --format=checkstyle | cs2pr
